title: Melissa Cianfarano
logo: docs/assets/profile.png
description: B.S. in Computer Science | Southern New Hampshire University | GPA 3.92 | Expected Graduation, May 2025 
#show_downloads:true
theme: jekyll-theme-minimal
